on:
  use: rss
  with:
    url: https://actionsflow.github.io/test-page/hn-rss.xml
  debug: true
steps:
  - id: command
    run: |
      echo title: ${{on.event.title}}
      echo contentSnippet: $contentSnippet
      echo link: $link
  - id: script1
    script: |
      console.log("title",${{on.event.title}});
      console.log("command", ${{steps[0].stdout}});
      return {"test": 1};
  - id: script2
    script: |
      console.log("script1 result", ${{steps[1].$return_value}})

  - id: script3
    path: ./format.ts