on:
  use: fetch-json
  with:
    url: http://hn.algolia.com/api/v1/search_by_date?tags=(story,poll,show_hn,ask_hn)&numericFilters=points>=100&hitsPerPage=50
  deduplicationKey: objectID
  itemsPath: hits
steps:
  use: ./to-json.ts
  args:
    - ${{event}}