
sources:
  - use: fetch
    args:
      - https://test.owenyoung.com/slim.json
    run: return ctx.result.json()
    itemsPath: hits
    key: objectID
    limit: 1
    force: true
steps: 
  - from: ./format.ts
    args:
      - ${{ctx.item}}
    assert: ctx.result.is_created_exists === true
